server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-details-service-auth
          uri: lb://USER-DETAILS-SERVICE
          predicates:
            - Path=/api/user/auth/**

        - id: user-details-service-info
          uri: lb://USER-DETAILS-SERVICE
          predicates:
            - Path=/api/user/info/**
#          filters:
#            - CustomJwtFilter

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    com.netflix:
      eureka: OFF
      discovery: OFF

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

