server:
  port: 8090

spring:
  application:
    name: api-gateway

logging:
  level:
    com.netflix:
      eureka: OFF
      discovery: OFF

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

