server:
  port: 8088

spring:
  application:
    name: file-media-service
  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    com.netflix:
      eureka: OFF
      discovery: OFF

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

