server:
  port: 8087

spring:
  application:
    name: posts-service

logging:
  level:
    com.netflix:
      eureka: OFF
      discovery: OFF


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

